#!/usr/bin/env python3
"""Per program x academic year: how sure are we of the roster?

    python3 scripts/tools/coverage_matrix.py

Combines data/intake/gaps/program*.json (observed / reconstructed / missing years, per-year significance,
complement, program length) with the DB roster_observations (names listed per year).
Writes data/verify/programs/coverage.csv and COVERAGE.md. Read-only on the DB.

Grades:
  A  observed roster, headcount within 1 of complement x length (or better)
  B  observed but headcount short by 2+, or reconstructed between observed years with no significant gap noted
  C  missing, or reconstructed with a gap marked significant (departures could be unseen)
  -  no gap file for the program (not audited)
"""
import csv, glob, json, re, sqlite3
from collections import Counter, defaultdict

YEARS = [f"{y}-{y + 1}" for y in range(2011, 2025)]
db = sqlite3.connect("db/neurosurgery_attrition.db")
progs = {r[0]: r[1] for r in db.execute("select program_id, name from programs")}
listed = defaultdict(int)
for pid, ay, n in db.execute("select program_id, academic_year, count(distinct name_as_listed) from roster_observations "
                             "where coalesce(role,'resident') not in ('fellow') group by 1, 2"):
    listed[(pid, ay)] = n

gaps = {}
for f in glob.glob("data/intake/gaps/program*.json"):
    g = json.load(open(f))
    gaps[g["program_id"]] = g


def as_int(v):
    if isinstance(v, int):
        return v
    m = re.search(r"\d+", str(v or ""))
    return int(m.group()) if m else None


rows = []
for pid, name in sorted(progs.items()):
    g = gaps.get(pid)
    for ay in YEARS:
        n = listed.get((pid, ay), 0)
        if not g:
            rows.append(dict(program_id=pid, program=name, year=ay, status="not_audited", significance="", listed=n,
                             expected="", grade="-"))
            continue
        ys = (g.get("year_status") or g.get("years") or {}).get(ay, {})
        if isinstance(ys, str):
            ys = {"status": ys}
        status = ys.get("status") or ("observed" if ay in g["observed_years"] else "reconstructed" if ay in g["reconstructed_years"]
                                      else "missing" if ay in g["missing_years"] else "")
        sig = (ys.get("significance") or "").lower()
        comp, length = as_int(g.get("complement_per_year")), as_int(g.get("program_length")) or 7
        first = as_int(g.get("first_class_year"))
        if first and int(ay[:4]) < first:
            status, grade, exp = "before_program", "", 0
        else:
            classes = length if not first else min(length, int(ay[:4]) - first + 1)
            exp = comp * classes if comp else None
            if status.startswith("observed"):
                grade = "A" if exp is None or n >= exp - 1 else "B"
            elif status.startswith("reconstructed") or status.startswith("bracketed"):
                grade = "C" if "signif" in sig and "not" not in sig and "insignif" not in sig else "B"
            elif status.startswith("missing"):
                grade = "C"
            else:
                grade = "B" if n else "C"
        rows.append(dict(program_id=pid, program=name, year=ay, status=status, significance=sig, listed=n,
                         expected=exp if exp is not None else "", grade=grade))

with open("data/verify/programs/coverage.csv", "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=list(rows[0]))
    w.writeheader()
    w.writerows(rows)

by_year = defaultdict(Counter)
tot = defaultdict(lambda: [0, 0])
for r in rows:
    by_year[r["year"]][r["grade"] or "n/a"] += 1
    tot[r["year"]][0] += r["listed"]
    tot[r["year"]][1] += r["expected"] or 0 if isinstance(r["expected"], int) else 0
L = ["# Roster coverage by program and year (auto-generated by scripts/tools/coverage_matrix.py)", "",
     "Grades: A = observed roster with full headcount; B = observed but short, or reconstructed between observed years; "
     "C = missing, or a gap flagged as significant (departures could be unseen); - = program not audited.", "",
     "| Year | A | B | C | not audited | before program existed | residents listed | expected (complement x length) |",
     "|---|---|---|---|---|---|---|---|"]
for ay in YEARS:
    c = by_year[ay]
    L.append(f"| {ay} | {c['A']} | {c['B']} | {c['C']} | {c['-']} | {c['n/a']} | {tot[ay][0]} | {tot[ay][1]} |")
L += ["", "## Grade C program-years (least confident)"]
cs = defaultdict(list)
for r in rows:
    if r["grade"] == "C":
        cs[(r["program_id"], r["program"])].append(r["year"][:4])
for (pid, name), ys in sorted(cs.items(), key=lambda x: -len(x[1])):
    L.append(f"- {pid} {name[:55]}: {', '.join(ys)}")
L += ["", "## Programs without an audit file", *[f"- {pid} {progs[pid]}" for pid in sorted(progs) if pid not in gaps]]
open("data/verify/programs/COVERAGE.md", "w").write("\n".join(L) + "\n")
print("\n".join(L[4:20]))
