#!/usr/bin/env python3
"""Merge phase-3 verification outputs and build the review files.

    python3 scripts/tools/phase3_merge.py

Reads data/verify/phase3/batch_*_in.json / batch_*_out.json and writes:

    data/verify/phase3/merged.json        one record per person (input + finding)
    data/verify/phase3/REVIEW.md          counts, disagreements, QA flags, open items
    data/verify/phase3/usnews_todo.json   people whose US News check is deferred/blocked/missing

Nothing is written to the database.
"""
import glob, json, os, re
from collections import Counter, defaultdict

D = "data/verify/phase3"
ins, outs = {}, {}
for f in sorted(glob.glob(f"{D}/batch_*_in.json")):
    n = re.search(r"batch_(\d+)_in", f).group(1)
    ins[n] = json.load(open(f))
    o = f.replace("_in.json", "_out.json")
    outs[n] = json.load(open(o)) if os.path.exists(o) else None

missing_batches = [n for n, o in outs.items() if o is None]
merged, missing_people = [], []
for n, rows in ins.items():
    found = {r.get("key"): r for r in (outs[n] or []) if isinstance(r, dict)}
    for r in rows:
        f = found.get(r["key"])
        if f is None:
            missing_people.append((n, r["key"], r["name"]))
            continue
        merged.append({"batch": n, **{k: r[k] for k in ("key", "name", "program_id", "program", "entry_year",
                                                         "first_seen", "last_seen", "last_pgy", "recorded_outcome", "tier")},
                       "finding": f})
json.dump(merged, open(f"{D}/merged.json", "w"), indent=1)

def rec_class(s):
    s = (s or "").upper()
    if "IN TRAINING" in s: return "in_training"
    if "COMPLETED" in s: return "completed"
    if "TRANSFERRED" in s: return "transferred"
    if "SWITCHED" in s: return "switched_specialty"
    if "LEFT MEDICINE" in s: return "left_medicine"
    return "left_or_unknown"

oc = Counter(m["finding"].get("outcome") for m in merged)
idc = Counter(m["finding"].get("identity") for m in merged)
chk = defaultdict(Counter)
for m in merged:
    for site, v in (m["finding"].get("checks") or {}).items():
        chk[site][v] += 1

# disagreements: agent flag, or outcome class differs from the recorded class
dis = []
for m in merged:
    f = m["finding"]; rc = rec_class(m["recorded_outcome"]); fo = f.get("outcome")
    if f.get("agrees_with_db") is False or (fo and rc != "left_or_unknown" and fo != rc):
        dis.append(m)
# tier-1 departures resolved as completed / in training (false 'left' records)
false_left = [m for m in merged if m["tier"] == 1 and m["finding"].get("outcome") in ("completed", "in_training")]

# QA: stale-page contamination -> the same specific Doximity quote used for people in different programs,
# or a quoted Doximity residency start >=2 years away from the recorded entry year
GENERIC = re.compile(r"^(Doximity Education & Training: )?Residency, Neurological Surgery, \d{4} - \d{4}")
ev = defaultdict(set)
yr_mismatch = []
for m in merged:
    for s in m["finding"].get("sources") or []:
        e = (s.get("evidence") or "").strip()
        if s.get("type") != "doximity": continue
        if len(e) > 40 and not GENERIC.match(e):
            ev[e].add((m["key"], m["program_id"]))
        y = re.search(r"Neurological Surgery,? (\d{4}) ?- ?\d{4}", e)
        if y and m.get("entry_year") and abs(int(y.group(1)) - int(m["entry_year"])) >= 2:
            yr_mismatch.append((m, y.group(0)))
dup_ev = {e: sorted(k for k, _ in ks) for e, ks in ev.items() if len({p for _, p in ks}) > 1}
weak_id = [m for m in merged if m["finding"].get("identity") in ("probable", "ambiguous", "not_found")]

todo = [{"key": m["key"], "name": m["name"], "program": m["program"],
         "usnews": (m["finding"].get("checks") or {}).get("usnews")} for m in merged
        if (m["finding"].get("checks") or {}).get("usnews") in (None, "deferred", "blocked")]
json.dump(todo, open(f"{D}/usnews_todo.json", "w"), indent=1)

L = ["# Phase 3 review (auto-generated by scripts/tools/phase3_merge.py)", "",
     f"People with a finding: {len(merged)} / {sum(len(v) for v in ins.values())}; "
     f"batches without output: {missing_batches or 'none'}; people missing from outputs: {len(missing_people)}", "",
     "## Outcomes found", *[f"- {k}: {v}" for k, v in oc.most_common()], "",
     "## Identity", *[f"- {k}: {v}" for k, v in idc.most_common()], "",
     "## Checks", *[f"- {s}: {dict(c)}" for s, c in chk.items()], "",
     f"## Recorded departures (tier 1) that were actually completed / still training: {len(false_left)}",
     *[f"- {m['name']} ({m['program'][:40]}): {m['finding'].get('outcome')} - {(m['finding'].get('outcome_detail') or '')[:140]}" for m in false_left], "",
     f"## Disagreements with the recorded outcome: {len(dis)}",
     *[f"- [{m['batch']}] {m['name']} ({m['program'][:40]}): recorded `{m['recorded_outcome'][:50]}` -> found `{m['finding'].get('outcome')}` "
       f"({m['finding'].get('identity')}). {(m['finding'].get('disagreement') or m['finding'].get('outcome_detail') or '')[:160]}" for m in dis], "",
     f"## QA: identical Doximity evidence quoted for different people (possible stale page reads): {len(dup_ev)}",
     *[f"- {ks}: \"{e[:100]}\"" for e, ks in dup_ev.items()], "",
     f"## QA: Doximity residency start >=2 years from recorded entry year (stale read or entry-year error): {len(yr_mismatch)}",
     *[f"- {m['name']} ({m['program'][:40]}) entry {m['entry_year']}: \"{q}\"" for m, q in yr_mismatch], "",
     f"## Weak identity (probable / ambiguous / not found): {len(weak_id)}",
     *[f"- {m['name']} ({m['program'][:40]}): {m['finding'].get('identity')}" for m in weak_id], "",
     f"## US News still to do: {len(todo)} (usnews_todo.json)", "",
     "## Missing people", *[f"- batch {n}: {k} {nm}" for n, k, nm in missing_people]]
open(f"{D}/REVIEW.md", "w").write("\n".join(L) + "\n")
print(f"merged {len(merged)}; outcomes {dict(oc)}; disagreements {len(dis)}; false-left {len(false_left)}; "
      f"dup-evidence {len(dup_ev)}; year-mismatch {len(yr_mismatch)}; usnews todo {len(todo)}; missing batches {missing_batches}; missing people {len(missing_people)}")
